// client/src/components/footer.tsx
export default function Footer() {
  return (
    <footer className="bg-[hsl(220,13%,9%)] border-t border-[hsl(216,7%,18%)] py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <p className="text-[hsl(215,20%,65%)]">
            © 2024 Raghav Rastogi. All rights reserved. Built with passion and modern web technologies.
          </p>
        </div>
      </div>
    </footer>
  );
}

// PortfolioApp/ClientApp/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer class="bg-primary border-t border-tertiary py-8">
      <div class="container">
        <div class="text-center">
          <p class="text-secondary">
            © 2024 Raghav Rastogi. All rights reserved. Built with passion and modern web technologies.
          </p>
        </div>
      </div>
    </footer>
  `,
  styles: [`
    .bg-primary { background-color: var(--bg-primary); }
    .border-tertiary { border-color: var(--bg-tertiary); }
    .text-secondary { color: var(--text-secondary); }
  `]
})
export class FooterComponent { }
